<?php

namespace Benj\benjBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdviseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdviseRepository extends EntityRepository
{
}
